### ISSUE TITLE
Ink Compiler Crash in Ink.InkParser.LogicLine()

### ISSUE THREAD

**Issue by deviant-dev** [inkle/ink#497]
### Summary
I've been getting compiler crashes as I type with the latest Inky 0.10.0 (which uses Ink 0.8.2). Luckily, Inky doesn't seem to mind and as I update the script, it 'uncrashes' when the compiler runs again. 😅

### Steps to Reproduce:
1. Start a new Ink project in Inky
2. Type in this script:
```
+ Test
    ~
```

### Result:
The live 'Preview' window shows this:
```
Sorry, the ink compiler crashed ☹

Here is some diagnostic information:

Unhandled Exception: 
Ink compiler had an unexpected error ☹

System.NullReferenceException: Object reference not set to an instance of an object.
   at Ink.InkParser.LogicLine()
   at Ink.StringParser.ParseObject(ParseRule rule)
   at Ink.StringParser.OneOf(ParseRule[] array)
   at Ink.InkParser.StatementAtLevel(StatementLevel level)
   at Ink.InkParser.<>c__DisplayClass134_0.b__0()
   at Ink.StringParser.ParseObject(ParseRule rule)
   at Ink.StringParser.Interleave[T](ParseRule ruleA, ParseRule ruleB, ParseRule untilTerminator, Boolean flatten)
   at Ink.InkParser.StatementsAtLevel(StatementLevel level)
   at Ink.InkParser.Parse()
   at Ink.Compiler.Compile()
   at Ink.CommandLineTool..ctor(String[] args)
   at Ink.CommandLineTool.Main(String[] args)
```

### Expected Result:
I see a warning about the incorrect syntax.

**Comment by deviant-dev** [comment]
Screenshot in case it helps:
![image](https://user-images.githubusercontent.com/33731102/48962647-5e194b80-efe7-11e8-8e5a-2707f5a89031.png)
