### ISSUE TITLE
Providing -> DONE as a divert target argument to a function breaks Inky/inklecate

### ISSUE THREAD

**Issue by furkle** [inkle/ink#562]
<a name="navigation"></a>
## Navigation 
1. [Navigation](#navigation)
1. [Description](#description)
1. [Reproduction](#reproduction)
1. [References](#references)

<a name="description"></a>
## Description
When one attempts to pass `-> DONE` or `-> END` as a divert target argument to a function, inklecate breaks in spectacular fashion. The error trace is as follows:
```
Sorry, the ink compiler crashed ☹

Here is some diagnostic information:

Unhandled Exception: 
Ink compiler had an unexpected error ☹

System.NullReferenceException: Object reference not set to an instance of an object.
   at Ink.Parsed.DivertTarget.ResolveReferences(Story context)
   at Ink.Parsed.Object.ResolveReferences(Story context)
   at Ink.Parsed.Divert.ResolveReferences(Story context)
   at Ink.Parsed.Object.ResolveReferences(Story context)
   at Ink.Parsed.Weave.ResolveReferences(Story context)
   at Ink.Parsed.Object.ResolveReferences(Story context)
   at Ink.Parsed.FlowBase.ResolveReferences(Story context)
   at Ink.Parsed.Story.ExportRuntime(ErrorHandler errorHandler)
   at Ink.Compiler.Compile()
   at Ink.CommandLineTool..ctor(String[] args)
   at Ink.CommandLineTool.Main(String[] args)
```

<a name="reproduction"></a>
## Reproduction
```
-> func(-> DONE)

=== func(-> to) ===
-> to
```

<a name="references"></a>
## References
* [Screenshot of error](https://user-images.githubusercontent.com/9000099/68518268-369fab00-0259-11ea-9ee9-c41d4822515a.png)

**Comment by joethephish** [comment]
Good catch, thanks! Fixed in 0e322720fba8a00115297952cded00344f93ef2b.
